### PR TITLE
fix: resolve concurrent map writes for audit cache

### LINKED ISSUE #418: audit function fails for concurrent map writes
#### Describe the bug

audit function fails for concurrent map writes and causes a crash of the service

#### Expected behavior

Audit works correctly without crash the service

#### Replication info

- Rönd version: v1.14.0
- Running mode: sidecar

#### Additional context

Stack trace:

<details><summary>Details</summary>
<p>

```txt
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 77598 [running]:
github.com/rond-authz/rond/internal/audit.(*SingleRecordCache).Store(0xc00051e3d8, 0xc000617100?)
	/app/internal/audit/cache.go:34 +0xf3
github.com/rond-authz/rond/internal/audit.init.func1({{0x13218c8, 0xc00073a660}, {0x1327750, 0xc000299260}, {0x1319d80, 0xc0000540e0}, 0xc00073aa20, {0x131dd48, 0xc000c8a97c}, 0x0, ...}, ...)
	/app/internal/audit/rego_builtin.go:51 +0xc2
github.com/rond-authz/rond/internal/audit.init.Function1.func2.1()
...
```

</p>
</details>

### PR DESCRIPTION
**Pull request by davidebianchi**
Resolves #418

### CODE REVIEW

**Comment by davidebianchi** [comment]
We could also enable the bench test to run with audit enabled, or to add a test case with the audit enabled. But the test on the sdk are useful (I also find the issue in the test logger in this way 😄)

File: internal/audit/agent.go [hunk 1]
```diff
@@ -21,14 +21,22 @@ type Labels = map[string]any
 type Agent interface {
 	Trace(context.Context, Audit)
 	Cache() AuditCache
-	SetGlobalLabels(labels Labels)
+}
+
+type AgentPool interface {
+	New() Agent
+	SetGlobalLabels(Labels)
```
Comment (fredmaggiowski) [inline internal/audit/agent.go:28]: I'm not convinced about this method being part of the pool behaviour. 

The method is intended to set labels during policy evaluation on a specific agent, if such labels are shared between multiple agents we might still have concurrency issues. 

Moreover I don't see changes to the builtin rego func that is using the method which feels odd, I'm worried about some type assertion that is making the code compile but that won't work at runtime

**Review by fredmaggiowski — CHANGES_REQUESTED** [review]

**Review by fredmaggiowski — APPROVED** [review]
LGTM
